/*
 * treqio_device_types.h
 *
 *  Created on: Jan 21, 2016
 *      Author: Diogo <diogocondeco@gmail.com>
 */

#ifndef SRC_TREQIO_TREQIO_DEVICE_TYPES_H_
#define SRC_TREQIO_TREQIO_DEVICE_TYPES_H_

typedef enum {
	TREQIO_DEVICE_OFF = 0, TREQIO_DEVICE_BOOTING, TREQIO_DEVICE_ON, TREQIO_DEVICE_SLEEP, TREQIO_POWER_SAVE_MODE,
} treqio_device_status_t;

typedef enum {
	TREQIO_MEMORY_OFF = 0x00, TREQIO_MEMORY_EEPROM, TREQIO_MEMORY_FLASH, TREQIO_MEMORY_ALL_ON,
} treqio_memory_status_t;

typedef enum {
	TREQIO_GPS_OFF = 0, TREQIO_GPS_ON, TREQIO_GPS_FIXED, TREQIO_GPS_LOST_FIX, TREQIO_GPS_RESET, TREQIO_GPS_SLEEP, TREIO_GPS_UPLOADING_EPHEMERIS,
} treqio_gps_status_t;

typedef enum {
	TREQIO_GPS_NO_EPHEMERIS = 0, TREQIO_GPS_ONLINE_EPHEMERIS, TREQIO_GPS_OFFLINE_EPHEMERIS,
} treqio_gps_ephemeris_type_t;

typedef enum {
	TREQIO_BLE_OFF = 0, TREQIO_BLE_ON, TREQIO_BLE_RESET, TREQIO_BLE_SCAN_DISABLED, TREQIO_BLE_SCAN_ENABLED, TREQIO_BLE_SCAN_ACTIVE,
} treqio_ble_status_t;

typedef struct {
	int latitude;
	int longitude;
	int altitude;
	uint8_t dop;
	uint8_t satellites;
	uint8_t fix;
	unsigned long long time;
} treqio_gps_position_t;

typedef enum {
	TREQIO_GSM_OFF = 0,
//	TREQIO_GSM_FIRST_BOOT_POWER_APPLIED,
//	TREQIO_GSM_FIRST_BOOT_POWER_ON_SIGNAL_APPLIED,
//	TREQIO_GSM_FIRST_BOOTING,
	TREQIO_GSM_BOOT_POWER_APPLIED,
	TREQIO_GSM_BOOT_POWER_ON_SIGNAL_APPLIED,
//	TREQIO_GSM_BOOT_POWER_ON_SIGNAL_REMOVED,
	TREQIO_GSM_BOOTING,
	TREQIO_GSM_BOOTED,
	TREQIO_GSM_POWER_ENABLED,
	TREQIO_GSM_POWER_ON,
	TREQIO_GSM_FIRST_BOOTED,
	TREQIO_GSM_ON,
	TREQIO_GSM_RESET,
	TREQIO_GSM_SLEEP,
	TREQIO_GSM_SEARCHING_CARRIER,
	TREQIO_GSM_CARRIER_AVAILABLE,
	TREQIO_GSM_COMMUNICATION_ACTIVE,
	TREQIO_GSM_COMMUNICATION_IDLE,
	TREQIO_GSM_COMMUNICATION_DONE,
	TREQIO_GSM_COMMUNICATION_FAILED,
} treqio_gsm_status_t;

typedef struct {
	uint32_t start;
	uint32_t end;
	uint32_t size;
	uint32_t uploadStart;
	uint32_t uploadEnd;
	uint32_t uploadSize;
	uint32_t removeStart;
	uint32_t removeSize;
} treqio_live_log_t;

typedef struct {
	uint32_t start;
	uint32_t upload;
	uint32_t end;
} treqio_back_log_t;

typedef struct {
	uint32_t ticks;
	uint8_t waiting;
} treqio_state_monitor_t;

typedef struct {
	uint32_t deviceId;
	uint32_t hwVersion;
	uint32_t fwVersion;
	uint32_t deviceReportPeriod;
	long long deviceLastDate;
	uint32_t bleSamplingPeriod;
	uint32_t bleSamplingWindow;
	uint32_t bleBeaconLifetime;
	uint32_t gpsSamplingPeriod;
	long long gpsOnlineEphemerisDate;
	long long gpsOfflineEphemerisDate;
	uint32_t gsmDataBlockSize;
	treqio_back_log_t backLog;
	treqio_gps_ephemeris_type_t gpsEphemerisType;
	treqio_gps_position_t gpsLastKnownLocation;
	uint8_t deviceDefaultConfig;
//	uint32_t logStartIdx;
//	uint32_t logEndIdx;
//	uint32_t logUploadIdx;
//	uint32_t flashDataStart;
//	uint32_t flashDataSize;
//	uint32_t flashDataEnd;
} treqio_system_config_t;

typedef struct {
	uint32_t gsmOnTime;
	uint32_t gpsRefreshRate;
	uint32_t gpsLastRefresh;
	uint32_t deviceLastReport;
	uint32_t gpsLastSample;
	uint32_t gpsEphemerisSize;
	uint32_t gpsEphemerisPosition;
	uint32_t bleLastSample;
	uint32_t delta;
	uint32_t bleBeaconsDbSize;
	treqio_live_log_t liveLog;
	treqio_gps_position_t gpsLocation;
	treqio_memory_status_t memoryStatus;
	treqio_device_status_t deviceStatus;
	treqio_ble_status_t bleStatus;
	treqio_gps_status_t gpsStatus;
	treqio_gps_ephemeris_type_t gpsEphemerisType;
	treqio_gsm_status_t gsmStatus;
	char batteryLevel;
	uint8_t treqioNewConfig;
	uint8_t timestamp;
	uint8_t bleNewBeacons;
	uint8_t nextBlockCounter;
	uint8_t newTimestamp;
	uint8_t waitingGsmConnection;
	uint8_t gsmFirstBooting;
	treqio_state_monitor_t liveMonitor;
	treqio_state_monitor_t backlogMonitor;
	//	uint8_t gsmWaitingDirectUploadResponse;
	//	uint8_t nextLogBlockCleared;
	//	uint32_t logCurrentBlockSize;
} treqio_system_status_t;

#define MAC_ADDRESS_SIZE								0x0006

#define TREQIO_GSM_TAG_SIZE								(sizeof(uint8_t))
#define TREQIO_GSM_TAG_DATA_SIZE						(sizeof(uint16_t))
#define TREQIO_GSM_TAG_CHECKSUM_SIZE					(sizeof(uint8_t))
#define TREQIO_GSM_TAG_HEADER_SIZE						(TREQIO_GSM_TAG_SIZE + TREQIO_GSM_TAG_DATA_SIZE)
#define TREQIO_GSM_TAG_OVERHEAD_SIZE					(TREQIO_GSM_TAG_HEADER_SIZE + TREQIO_GSM_TAG_CHECKSUM_SIZE)

#define TREQIO_WEB_TAG_SIZE								(sizeof(uint8_t))
#define TREQIO_WEB_TAG_DATA_SIZE						(sizeof(uint8_t))
//#define TREQIO_WEB_TAG_CHECKSUM_SIZE					(sizeof(uint8_t))
#define TREQIO_WEB_TAG_HEADER_SIZE						(TREQIO_WEB_TAG_SIZE + TREQIO_WEB_TAG_DATA_SIZE)
#define TREQIO_WEB_TAG_OVERHEAD_SIZE					(TREQIO_WEB_TAG_HEADER_SIZE)

#define TREQIO_FRAME_SIZE								64

#define TREQIO_INFO_BATTERY_TAG							0x81
#define TREQIO_INFO_BATTERY_SIZE						sizeof(uint8_t)
#define TREQIO_INFO_BATTERY_TAG_SIZE					(TREQIO_WEB_TAG_HEADER_SIZE + TREQIO_INFO_BATTERY_SIZE)

#define TREQIO_INFO_GPS_LOCATION_TAG					0x82
#define TREQIO_INFO_GPS_LATITUDE_SIZE					sizeof(int)
#define TREQIO_INFO_GPS_LONGITUDE_SIZE					sizeof(int)
#define TREQIO_INFO_GPS_ALTITUDE_SIZE					sizeof(int)
#define TREQIO_INFO_GPS_DILUTION_SIZE					sizeof(uint8_t)
#define TREQIO_INFO_GPS_LOCATION_SIZE					(TREQIO_INFO_GPS_LATITUDE_SIZE + TREQIO_INFO_GPS_LONGITUDE_SIZE + TREQIO_INFO_GPS_ALTITUDE_SIZE + TREQIO_INFO_GPS_DILUTION_SIZE)
#define TREQIO_INFO_GPS_LOCATION_TAG_SIZE				(TREQIO_WEB_TAG_HEADER_SIZE + TREQIO_INFO_GPS_LOCATION_SIZE)

#define TREQIO_INFO_BEACON_TAG							0x83
#define TREQIO_INFO_BEACON_SIZE							(6*(sizeof(uint8_t)) + sizeof(int8_t) + sizeof(int8_t) + sizeof(int8_t) + sizeof(uint8_t)) //	delta, battery, temperature, mac[MAC_ADDRESS_SIZE], rssi, event;
#define TREQIO_INFO_BEACON_TAG_SIZE						(TREQIO_WEB_TAG_HEADER_SIZE + TREQIO_INFO_BEACON_SIZE)
//#define TREQIO_INFO_BEACON_UUID_SIZE					(16*sizeof(uint8_t))
//#define TREQIO_INFO_BEACON_MAC_ADDR_SIZE				(6*sizeof(uint8_t))
//#define TREQIO_INFO_BEACON_MAJOR_SIZE					sizeof(uint16_t)
//#define TREQIO_INFO_BEACON_MINOR_SIZE					sizeof(uint16_t)
//#define TREQIO_INFO_BEACON_RSSI_SIZE					sizeof(uint8_t)
//#define TREQIO_INFO_BEACON_BATTERY_SIZE					sizeof(uint8_t)
//#define TREQIO_INFO_BEACON_FW_VERSION_SIZE				sizeof(uint16_t)
//#define TREQIO_INFO_BEACON_TEMPERATURE_SIZE				sizeof(uint8_t)
//#define TREQIO_INFO_BEACON_BEACON_EVENT_SIZE			sizeof(uint8_t)
//#define TREQIO_INFO_BEACON_TREQ_EVENT_SIZE				sizeof(uint8_t)
//#define TREQIO_INFO_BEACON_FULL_TAG_DATA_SIZE			(TREQIO_INFO_BEACON_UUID_SIZE + TREQIO_INFO_BEACON_MAC_ADDR_SIZE + TREQIO_INFO_BEACON_RSSI_SIZE + TREQIO_INFO_BEACON_BATTERY_SIZE + TREQIO_INFO_BEACON_FW_VERSION_SIZE + TREQIO_INFO_BEACON_TEMPERATURE_SIZE + TREQIO_INFO_BEACON_BEACON_EVENT_SIZE + TREQIO_INFO_BEACON_TREQ_EVENT_SIZE)
//#define TREQIO_INFO_BEACON_MAC_TAG_DATA_SIZE			(TREQIO_INFO_BEACON_MAC_ADDR_SIZE + TREQIO_INFO_BEACON_MAJOR_SIZE + TREQIO_INFO_BEACON_MINOR_SIZE + TREQIO_INFO_BEACON_RSSI_SIZE + TREQIO_INFO_BEACON_BATTERY_SIZE + TREQIO_INFO_BEACON_FW_VERSION_SIZE + TREQIO_INFO_BEACON_TEMPERATURE_SIZE + TREQIO_INFO_BEACON_BEACON_EVENT_SIZE + TREQIO_INFO_BEACON_TREQ_EVENT_SIZE)
//#define TREQIO_INFO_BEACON_FULL_TAG_SIZE				(TREQIO_REPORT_TAG_HEADER_SIZE + TREQIO_INFO_BEACON_FULL_TAG_DATA_SIZE + TREQIO_TAG_CHECKSUM_SIZE)
//#define TREQIO_INFO_BEACON_MAC_TAG_SIZE					(TREQIO_REPORT_TAG_HEADER_SIZE + TREQIO_INFO_BEACON_MAC_TAG_DATA_SIZE + TREQIO_TAG_CHECKSUM_SIZE)

#define TREQIO_INFO_GATEWAY_STATUS						0x84
#define TREQIO_INFO_GATEWAY_STATUS_SIZE					sizeof(uint8_t)
#define TREQIO_INFO_GATEWAY_STATUS_NO_GPS				0x00
#define TREQIO_INFO_GATEWAY_STATUS_GPS_FIX				0x01
#define TREQIO_INFO_GATEWAY_STATUS_TAG_SIZE				(TREQIO_WEB_TAG_HEADER_SIZE + TREQIO_INFO_GATEWAY_STATUS_SIZE)

#define TREQIO_INFO_DELTATIME_TAG						0xFE
#define TREQIO_INFO_DELTATIME_SIZE						sizeof(uint32_t)
#define TREQIO_INFO_DELTATIME_TAG_SIZE					(TREQIO_WEB_TAG_HEADER_SIZE + TREQIO_INFO_DELTATIME_SIZE)

#define TREQIO_INFO_TIMESTAMP_TAG						0xFB
#define TREQIO_INFO_TIMESTAMP_SIZE						(sizeof(long long))
#define TREQIO_INFO_TIMESTAMP_TAG_SIZE					(TREQIO_WEB_TAG_HEADER_SIZE + TREQIO_INFO_TIMESTAMP_SIZE)

#define TREQIO_CONFIG_DEVICE_MAC_ADDRESS				0x4D //M
#define TREQIO_CONFIG_DEVICE_MAC_ADDRESS_SIZE			MAC_ADDRESS_SIZE
#define TREQIO_CONFIG_DEVICE_MAC_ADDRESS_TAG_SIZE		(TREQIO_GSM_TAG_HEADER_SIZE + TREQIO_CONFIG_DEVICE_MAC_ADDRESS_SIZE)

#define TREQIO_CONFIG_RECEIVED_TAG						0x20
#define TREQIO_CONFIG_NOT_RECEIVED						0x00
#define TREQIO_CONFIG_RECEIVED_SUCCESSFUL				0x01
#define TREQIO_CONFIG_RECEIVED_TAG_SIZE					(sizeof(uint8_t))

#define TREQIO_CONFIG_DEVICE_REPORT_RATE				0x21
#define TREQIO_CONFIG_DEVICE_REPORT_RATE_SIZE			(sizeof(uint32_t))
#define TREQIO_CONFIG_DEVICE_REPORT_RATE_MIN			1000
#define TREQIO_CONFIG_DEVICE_REPORT_RATE_MAX			(24*60*60*1000)

#define TREQIO_CONFIG_GPS_SAMPLING_RATE					0x22
#define TREQIO_CONFIG_GPS_SAMPLING_RATE_TAG_SIZE		(sizeof(uint32_t))
#define TREQIO_CONFIG_GPS_SAMPLING_RATE_MIN				1000
#define TREQIO_CONFIG_GPS_SAMPLING_RATE_MAX				(24*60*60*1000)

#define TREQIO_CONFIG_BLE_SAMPLING_RATE					0x23
#define TREQIO_CONFIG_BLE_SAMPLING_RATE_TAG_SIZE		(sizeof(uint32_t))
#define TREQIO_CONFIG_BLE_SAMPLING_RATE_MIN				100
#define TREQIO_CONFIG_BLE_SAMPLING_RATE_MAX				(24*60*60*1000)

#define TREQIO_CONFIG_BLE_SAMPLING_WINDOW				0x24
#define TREQIO_CONFIG_BLE_SAMPLING_WINDOW_TAG_SIZE		(sizeof(uint32_t))
#define TREQIO_CONFIG_BLE_SAMPLING_WINDOW_MIN			100
#define TREQIO_CONFIG_BLE_SAMPLING_WINDOW_MAX			0x24

#define TREQIO_CONFIG_BLE_BEACON_ALIVE_WINDOW			0x25
#define TREQIO_CONFIG_BLE_BEACON_ALIVE_WINDOW_TAG_SIZE	(sizeof(uint32_t))
#define TREQIO_CONFIG_BLE_BEACON_ALIVE_WINDOW_MIN		1000
#define TREQIO_CONFIG_BLE_BEACON_ALIVE_WINDOW_MAX		(24*60*60*1000)

#define TREQIO_CONFIG_GPS_EPHEMERIS_TYPE				0x26
#define TREQIO_CONFIG_GPS_EPHEMERIS_TYPE_TAG_SIZE		(sizeof(uint8_t))
#define TREQIO_CONFIG_GPS_EPHEMERIS_TYPE_NO_EPHEMERIS	0x00
#define TREQIO_CONFIG_GPS_EPHEMERIS_TYPE_ONLINE			0x01
#define TREQIO_CONFIG_GPS_EPHEMERIS_TYPE_OFFLINE		0x02

#define TREQIO_CONFIG_BLE_RSSI_DETECT_LEVEL				0x27
#define TREQIO_CONFIG_BLE_RSSI_DETECT_LEVEL_TAG_SIZE	sizeof(int8_t)
#define TREQIO_CONFIG_BLE_RSSI_DETECT_LEVEL_MIN			0
#define TREQIO_CONFIG_BLE_RSSI_DETECT_LEVEL_MAX			127

#define TREQIO_INCOMING_CONFIGURATION_TAG				0x43

#define TREQIO_REQUEST_OFFLINE_EPHEMERIS_SIZE_TAG		0x14
#define TREQIO_REQUEST_OFFLINE_EPHEMERIS_SIZE_SIZE		(sizeof(uint8_t))
#define TREQIO_REQUEST_OFFLINE_EPHEMERIS_SIZE_TAG_SIZE	(TREQIO_TAG_HEADER_SIZE + TREQIO_REQUEST_OFFLINE_EPHEMERIS_SIZE_SIZE)
#define TREQIO_INCOMING_OFFLINE_EPHEMERIS_SIZE_TAG		(TREQIO_REQUEST_OFFLINE_EPHEMERIS_SIZE_TAG)
#define TREQIO_INCOMING_OFFLINE_EPHEMERIS_SIZE_SIZE		(sizeof(uint32_t))
#define TREQIO_INCOMING_OFFLINE_EPHEMERIS_SIZE_TAG_SIZE	(TREQIO_TAG_HEADER_SIZE + TREQIO_INCOMING_OFFLINE_EPHEMERIS_SIZE_SIZE)

#define TREQIO_REQUEST_ONLINE_EPHEMERIS_SIZE_TAG		0x15
#define TREQIO_REQUEST_ONLINE_EPHEMERIS_SIZE_SIZE		(sizeof(uint8_t))
#define TREQIO_REQUEST_ONLINE_EPHEMERIS_SIZE_TAG_SIZE	(TREQIO_TAG_HEADER_SIZE + TREQIO_REQUEST_ONLINE_EPHEMERIS_SIZE_SIZE)
#define TREQIO_INCOMING_ONLINE_EPHEMERIS_SIZE_TAG		(TREQIO_REQUEST_ONLINE_EPHEMERIS_SIZE_TAG)
#define TREQIO_INCOMING_ONLINE_EPHEMERIS_SIZE_SIZE		(sizeof(uint32_t))
#define TREQIO_INCOMING_ONLINE_EPHEMERIS_SIZE_TAG_SIZE	(TREQIO_TAG_HEADER_SIZE + TREQIO_INCOMING_ONLINE_EPHEMERIS_SIZE_SIZE)

#define TREQIO_REQUEST_EPHEMERIS_DATA_BLOCK_TAG			0x16
#define TREQIO_REQUEST_EPHEMERIS_DATA_BLOCK_SIZE		(sizeof(uint32_t))
#define TREQIO_REQUEST_EPHEMERIS_DATA_BLOCK_TAG_SIZE	(TREQIO_TAG_HEADER_SIZE + TREQIO_REQUEST_EPHEMERIS_DATA_BLOCK_SIZE)
#define TREQIO_INCOMING_EPHEMERIS_DATA_BLOCK_TAG		(TREQIO_REQUEST_EPHEMERIS_DATA_BLOCK_TAG)
#define TREQIO_INCOMING_EPHEMERIS_DATA_BLOCK_SIZE		(sizeof(uint32_t))
#define TREQIO_INCOMING_EPHEMERIS_DATA_BLOCK_TAG_SIZE	(TREQIO_TAG_HEADER_SIZE + TREQIO_INCOMING_EPHEMERIS_DATA_BLOCK_SIZE)

#define TREQIO_UART_DATA_RX_BUFFER_SIZE					600

#define TREQIO_TEMP_FRAME_SIZE							32

#define TREQIO_GSM_OPERATIONS_TIMEOUT_MS				5000

#endif /* SRC_TREQIO_TREQIO_DEVICE_TYPES_H_ */
